apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-project
  labels:
    app: maven
spec:
  replicas: 3
  selector:
    matchLabels:
      app: maven
  template:
    metadata:
      labels:
        app: maven
    spec:
      containers:
      - name: maven-app
        image: sohrab109/maven:30
        ports:
        - containerPort: 8080
